name: Python Quality
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Asenna Flake8
      run: pip install flake8
      
    # OSA 1: Etsii vain koodin rikkovat virheet (esim. puuttuva sulku)
    - name: Aja Linteri (Vakavat virheet)
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    # OSA 2: Etsii tyylivirheet (esim. liian pitk√§t rivit)
    - name: Aja Linteri (Tyylivirheet)
      run: flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
